#db service
apiVersion: v1
kind: Service
metadata:
  name: fiap-ms-wallet-db
spec:
  selector:
    app: fiap-ms-wallet-db
  ports:
  - protocol: 'TCP'
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
#db deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-wallet-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-ms-wallet-db
  template:
    metadata:
      labels:
        app: fiap-ms-wallet-db
    spec:
      containers:
        - name: fiap-ms-wallet-db
          image: mongo:latest
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: password
          - name: MONGO_INITDB_DATABASE
            value: fiap-ms-wallet
---
#api service
apiVersion: v1
kind: Service
metadata:
  name: fiap-ms-wallet
spec:
  selector:
    app: fiap-ms-wallet
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
#api deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-ms-wallet
  labels:
    app: fiap-ms-wallet
spec:
  selector:
    matchLabels:
        app: fiap-ms-wallet
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fiap-ms-wallet
    spec:
      containers:
        - name: fiap-ms-wallet
          image: jvitoralmeida/fiap.ms-wallet:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: password
          - name: MONGO_INITDB_DATABASE
            value: fiap.ms-store
