# docker-compose.yml

version: '3'
services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sacred
    networks:
      - omniboard
    restart: always
    volumes:
      - ./mongo:/data/db
  mongoku:
    image: huggingface/mongoku
    networks:
      - omniboard
    ports:
      - 3100:3100
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb://user:password@mongo:27017/?authMechanism=SCRAM-SHA-1"
    depends_on:
      - mongo
    restart: always

networks:
  omniboard: